### Files operated are UK-makers.csv and the UK-makerspaces-identifiable.csv

In [6]:
from pyspark.sql import SparkSession,functions as fs
session= SparkSession.builder.appName("UK MAKERS SPACE").master("local[*]").getOrCreate()

dataFrame = session.read

dataFramePC = dataFrame.option("header","true").option("inferSchema","true")\
.csv("/Users/ashishdwivedi/anaconda3/envs/ml-lib/Spark/Codes/in/uk-postcode.csv")

dataFrameUK = dataFrame.option("header","true").option("inferSchema","true")\
.csv("/Users/ashishdwivedi/anaconda3/envs/ml-lib/Spark/Codes/in/uk-makerspaces-identifiable-data.csv")\
.withColumn("Postcode",fs.concat_ws("",fs.col("Postcode"),fs.lit(" ")))

In [9]:
#joined = dataFrameUK.join(dataFramePC, dataFrameUK["Postcode"].startswith(dataFramePC["Postcode"]), "left_outer")

joinFrame = dataFramePC.join(dataFrameUK,dataFrameUK["Postcode"].startswith(dataFramePC["Postcode"]),"left_outer")

In [10]:
print("Joined data")
joinFrame.groupBy("Region").count().show(200)

Joined data
+--------------------+-----+
|              Region|count|
+--------------------+-----+
|           Worcester|   11|
|           Charnwood|    2|
|      North Kesteven|    2|
|                Arun|    3|
|       Epping Forest|    6|
|             Waveney|    3|
|              Stroud|    5|
| Nuneaton & Bedworth|    3|
|          New Forest|    8|
|           Newmarket|    1|
|              Maldon|    2|
|           Sedgemoor|    1|
|            Worthing|    6|
|            Brighton|    1|
|           Guildford|    8|
|              Bolton|    9|
|Central Bedfordshire|    8|
|      North Tyneside|    7|
|           Bradford |    1|
|        Surrey Heath|    5|
|      Wellingborough|    2|
|              Slough|    2|
|          Spelthorne|    5|
|         West Dorset|    6|
|          Shropshire|   20|
|           Hampshire|   27|
|      Aylesbury Vale|    8|
|           Lichfield|    3|
|           Banbridge|    2|
|    Scottish Borders|   17|
|           Inverness|    1|
|              Jersey|    2|
|       Staffordshire|   21|
|           Ballymena|    3|
|           Edinburgh|   23|
|        East Lothian|   12|
|          Sunderland|   12|
|           High Peak|    4|
|        Chesterfield|    5|
|         West London|    1|
|            Bradford|   22|
|             Babergh|    3|
|          Manchester|   26|
|          Rossendale|    2|
|             Lisburn|    2|
|          Uttlesford|    4|
|            Ramsgate|    1|
|            Tamworth|    3|
|             Croydon|   12|
|           Bassetlaw|    3|
|          Wandsworth|    5|
|             Rutland|    1|
|              Bexley|    9|
|          Midlothian|   10|
|                Hull|    1|
|      Orkney Islands|    3|
|  Kingston upon Hull|    9|
|        Christchurch|    1|
|            Coventry|    7|
|          Eastbourne|    4|
|             Wycombe|    8|
|              Oxford|    7|
|             Lambeth|   12|
|Cheshire West and...|   15|
|         Broadstairs|    1|
|      West Berkshire|    3|
|North East Derbys...|    3|
|           Craigavon|    6|
|     Tunbridge Wells|    4|
|             Glasgow|   35|
|             Swindon|   12|
|  Telford and Wrekin|    9|
|           Cambridge|   10|
|     North Yorkshire|   18|
|                Wyre|    3|
|            Rochdale|    6|
|               Powys|    9|
|             Horsham|    5|
|Barking and Dagenham|    5|
|           Wakefield|   11|
|Blackburn with Da...|    3|
|             Purbeck|    2|
|             Belfast|   18|
|            Daventry|    4|
|           Hertsmere|    4|
|      South Somerset|    8|
|           Blackburn|    1|
|             Cardiff|   20|
|              Wirral|   21|
|     Suffolk Coastal|    8|
|           Brentwood|    4|
|              Camden|   20|
|              Woking|    3|
|Dungannon and Sou...|    6|
|            Chiltern|    4|
|           Gravesham|    3|
|   Neath Port Talbot|    6|
|           Greenwich|    7|
|       Cannock Chase|    3|
|           Fermanagh|    5|
|                Ards|    2|
|              Dundee|    5|
|             Ashford|    7|
|      St Edmundsbury|    6|
|                null|    1|
|           Gateshead|   12|
|              Dudley|   10|
|             Norwich|    1|
|           Doncaster|   14|
|     West Lancashire|    3|
|  North Lincolnshire|    9|
|               Corby|    2|
|               Moray|    8|
|            Sandwell|    9|
|          Bromsgrove|    2|
|          North Down|    4|
|              Newham|    7|
|              London|   16|
|            Thurrock|    7|
|            Barnsley|    8|
|       Ribble Valley|    1|
|         East Dorset|    3|
|            Copeland|   13|
| Vale of White Horse|    3|
|         Birmingham |    4|
|              Antrim|    1|
|   Stratford-on-Avon|    7|
|              Oldham|    8|
|           Sevenoaks|    6|
|Weymouth and Port...|    3|
|          Birmingham|   42|
|       Tower Hamlets|   10|
|           Eastleigh|    5|
|            Guernsey|   10|
|             Burnley|    3|
|              Barnet|   10|
|              Exeter|   27|
|            Hounslow|    8|
|            Knowsley|    5|
|          Harborough|    1|
|       Pembrokeshire|   17|
|               Derby|    9|
|    Derbyshire Dales|    5|
|              Harrow|    7|
|           Leicester|   23|
|             Salford|    9|
|           Mansfield|    3|
|       Monmouthshire|    6|
|   Barrow-in-Furness|    4|
|                Adur|    2|
|        West Norfolk|    9|
|            Ayrshire|    1|
|             Crawley|    4|
|          Winchester|    4|
|        North Dorset|    4|
|            Waverley|    7|
|         Mole Valley|    6|
|             Chorley|    2|
|   East Renfrewshire|    3|
|         Isle of Man|    9|
|Hinckley and Bosw...|    1|
|            Dartford|    6|
|            Highland|   85|
|            Cherwell|    7|
|              Mendip|    5|
|            Tendring|    6|
|           Rotherham|    9|
|Kensington and Ch...|    8|
|         Bournemouth|   10|
|          Mid Sussex|    6|
|       Hertfordshire|    1|
|           Islington|    8|
|  East Hertfordshire|    8|
|               Selby|    1|
|      South Kesteven|    6|
|            Plymouth|    9|
|       County Antrim|    2|
|          Caerphilly|    5|
|               Brent|    3|
|       Blaenau Gwent|    4|
|         Argyllshire|   46|
| North Hertfordshire|    6|
|           Wiltshire|   17|
|             Dacorum|    6|
|    Newry and Mourne|    2|
|          West Devon|    3|
|         Test Valley|    5|
|            Hastings|    4|
|     Welwyn Hatfield|    5|
|          Flintshire|    5|
|            Haringey|    6|
|           Sheffield|   24|
|             Bromley|   12|
|              Sefton|    9|
| Newark and Sherwood|    5|
|        Wigtownshire|    2|
|           Wokingham|    6|
|           Mid Devon|    2|
|       Kinross-Shire|    1|
|South Northampton...|    2|
+--------------------+-----+
only showing top 200 rows